### ISSUE TITLE
Scribe-iOS Bangla localization

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#12]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would do localization of the Scribe-iOS texts into Bangla (Bengali). It's currently blocked by the following issues:

- scribe-org/Scribe-iOS#392
- scribe-org/Scribe-i18n#9
- scribe-org/Scribe-i18n#8 

We'll use the decided on tool for localization to do the translations, and then the process created in the above issues will add them into the `.xcstrings` file where they can be applied to the application if the user has selected Bangla as their base or chosen language :)

@mhmohona, can you write in here so I can assign as we discussed? 🌐😊

**Comment by andrewtavis** [comment]
Unblocked as all's set up 😊 Get to this when you can, @mhmohona!

**Comment by andrewtavis** [comment]
You'd be welcome to add in the Bangla JSON with a few localizations for this issue, @mhmohona! I can then turn on the option in Weblate :)

**Comment by axif0** [comment]
Want to work on this..

**Comment by mhmohona** [comment]
Yes sure @axif0!

**Comment by andrewtavis** [comment]
Thanks for picking this up, @axif0!

**Comment by andrewtavis** [comment]
Got the language request. Feel free to send along the JSON file the localizations that you want to do locally, and if you want to do some on Weblate we can do that after merging in the JSON.
