### ISSUE TITLE
Create JSON to XML conversion process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#27]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

One thing that's needed for integrating Scribe-i18n with Scribe-Android is adding in a Python script that would convert the JSON files into XML files that are valid for use within the Android app. We can then add in the script to [.github/workflows/xcstrings_conversion.yml](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/workflows/xcstrings_conversion.yml) so that it runs on merge (likely rename it to json_file_conversion or something that's iOS/Android agnostic).

Happy to help plan this out and potentially get to it myself at some point! 😊

**Comment by andrewtavis** [comment]
Quoting @angrezichatterbox from https://github.com/scribe-org/Scribe-Android/issues/44#issuecomment-2277611740:

> I don't have much idea about how localization is in iOS. But I haven't seen a single strings.xml file for all the languages in any Android project yet. So could I put each language into its own XML or should I look into having a single strings.xml file for all languages? Should I make the discussions over there in the issue ?

I'd say it's totally fine to have an XML file per language! As you see fit :) The end of this could be a directory of XML files that we'd then use for the different localizations?

**Comment by angrezichatterbox** [comment]
I have made a pull request for the issue. Please do suggest any changes to make to the scripts. :)

**Comment by andrewtavis** [comment]
Closed by #36 🎉 Thanks so much for the work here, @angrezichatterbox! This will definitely make Android development a lot easier moving forward :)
