### ISSUE TITLE
Refactor Scribe-i18n and have JSON scripts use json package

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#37]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would be a general refactor of the Scribe-i18n project and would also make some edits to the [Scripts](https://github.com/scribe-org/Scribe-i18n/tree/main/Scribe-i18n/Scripts) to assure that they're using the Python `json` package.

Specifically:
- Move the iOS scripts into an `iOS` directory under `Scribe-i18n/Scripts`
    - The same for the Android scripts to an `Android` directory
- Update the [conversion workflow](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/workflows/xcstrings_conversion.yml) to reference these new paths
- Update all scripts to assure that they're using the [Python json package](https://docs.python.org/3/library/json.html)

Happy to support with this as I can! 😊

- Note: We should first bring in #36 before we work on this so we can include the Android changes

**Comment by andrewtavis** [comment]
CC @Jag-Marcel :) Would you have interest in working on this one? We could also try the fix to the conversion script in here as well, or I'd be happy to make a separate issue for that!

**Comment by Jag-Marcel** [comment]
> CC @Jag-Marcel :) Would you have interest in working on this one? We could also try the fix to the conversion script in here as well, or I'd be happy to make a separate issue for that!

Yeah, I could work on this one, I think it makes sense to include that as well, since it's related.

**Comment by andrewtavis** [comment]
Nice, @Jag-Marcel :) The PR's now merged, so we're good to work on this as well!

**Comment by andrewtavis** [comment]
Let me know if you have some thoughts on this merge commit's error, @Jag-Marcel :)

https://github.com/scribe-org/Scribe-i18n/actions/runs/10400331540/job/28800679978

**Comment by Jag-Marcel** [comment]
> Let me know if you have some thoughts on this merge commit's error, @Jag-Marcel :)
> 
> https://github.com/scribe-org/Scribe-i18n/actions/runs/10400331540/job/28800679978

Maybe we just need to remove the period from the address? as in `Scripts/Android/convert_jsons_to_strings.py` instead of `./Scripts/Android/convert_jsons_to_strings.py`

**Comment by andrewtavis** [comment]
Ya that's a good thought :) I'll do this later tonight when I redo some things so that all of the JSONs are in a single folder as well :)

**Comment by andrewtavis** [comment]
Need to switch that on Weblate too, but then better that than to have them all there when we have 20 :)

**Comment by andrewtavis** [comment]
Let's keep an eye on this, @Jag-Marcel, but hopefully it'll work soon :) We did not need the `./` for sure, and I think adding in the full path was needed because we didn't define the directory earlier in the script. No edits to the JSONs this most recent time, so we're not getting a run, but we'll see when the next localizations come though :)

Thanks for the work here! I'll close this and we can hot fix any issues that might come from here 😊
