### ISSUE TITLE
Usage of proprietary software (Transifex)

### ISSUE THREAD

**Issue by nemobis** [scribe-org/Scribe-i18n#5]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

This repository appears set to use Transifex, a proprietary software service. Instead it should follow FLOSS best practices for iOS and Android projects and use a service which supports them, like our own [translatewiki.net](https://translatewiki.net/) or possibly [Weblate](https://weblate.org/).

Free Software and Free Knowledge are core Wikimedia principles. It is not acceptable to subject Wikimedia translators in hundreds of languages to the usage of proprietary software.

Help is available in the Wikimedia technical community to follow i18n best practices. I'm also confused as to why this is a separate repository: that usually makes it a pain to follow a method of [continuous translation](https://translatewiki.net/wiki/Translating:Localisation_for_developers#Continuous_translation), which is necessary to ensure high quality of translations.

**Comment by andrewtavis** [comment]
Hey @nemobis 👋 I think there might be some confusion here. The purpose of this repository is only to provide localization strings to Scribe application user interfaces. Nothing that's being done here is going to be on wiki. I'm not really sure if translatewiki is appropriate given the goal. I've looked at weblate before and made the decision for transifex as a free for open source option as the user experience was dramatically better. We can potentially revisit this as we've yet to start using this repository. 

@wkyoshida, something to consider here is whether we want to just do a direct git based translation of the strings at first. Most of what we're doing here is individual words or a few minor sentences for installation directions. Beyond that we have long texts for the privacy policy, but then it might work with just having the texts and asking the community to make a PR directly.

**Comment by wkyoshida** [comment]
TBH I haven't looked at the comparison between the three options to say for sure. I'll have to look into them. I did notice though that [Commons App](url) and [Kiwix](https://github.com/kiwix) (other [New Developers projects](https://www.mediawiki.org/wiki/New_Developers#Choose_a_software_project)) seem to actually be on [translatewiki.net](https://translatewiki.net/). So perhaps it could be an option for us? :shrug: 

We'll have to look into it. But if anything, I think a direct git-based approach like you said could also be fine to start with, and then we can look into the options above to help expand translations.

**Comment by andrewtavis** [comment]
8dd22be just removed all references to Transifex along with changes to simplify the repo as much as we can as it'll be imbedded in other applications. We'll be doing a Git based localization process until we need to switch to something else. Thanks for raising these concerns, @nemobis! Closing this issue now 😊

**Comment by andrewtavis** [comment]
Hey @nemobis 👋 Wanted to reach out again and thank you for raising the concerns here. We've switched the project over to Weblate at this point, and conversations in activist are pointing towards that project doing the same :)
