### ISSUE TITLE
Start Scribe application Hindi internationalization

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#51]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in an `hi.json` file to the [Scribe-i18n/jsons](https://github.com/scribe-org/Scribe-i18n/tree/main/Scribe-i18n/jsons) directory with a few localizations of some strings that are found in [Scribe-i18n/jsons/en-US.json](https://github.com/scribe-org/Scribe-i18n/blob/main/Scribe-i18n/jsons/en-US.json). This would thus start the i18n process for this language, with it also being added on to Scribe's [Weblate project](https://hosted.weblate.org/projects/scribe/scribe-i18n/) for further work.

Please let us know if you have interest in working on this, and we'll be happy to provide any help that's needed!

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis, Can I be assigned this issue? I want to work on I18n too and I think this issue will make a good start. I would like to do a little research and then solve this issue:)

**Comment by andrewtavis** [comment]
Sounds great, @KesharwaniArpita! 😊

**Comment by andrewtavis** [comment]
Let us know if you have any questions. You don't have to do the full localization for this, but just a bit and then adding in the file to this repo. I'll then add it to Weblate for you and others to work with in the UI :)

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis, I wanted to give out my understanding of working on this issue, 
1. I have to register with Weblate.
2. Create a Hindi language file and translate the strings. I will get a JSON file as an output later.
3. I'll have to add the .json file in the repo(I am not sure if I'll be the one adding the file or if will it be done by Weblate?).

Can you guide me through this and tell me where am I missing anything?

**Comment by andrewtavis** [comment]
Responses on the above, @KesharwaniArpita :) 

> 1. I have to register with Weblate.

Yea and link your GitHub account :) 

> 2. Create a Hindi language file and translate the strings. I will get a JSON file as an output later.
> 3. I'll have to add the .json file in the repo(I am not sure if I'll be the one adding the file or if will it be done by Weblate?).

You can commit an `hi.json` file via a PR here with as many localizations as you want at first and then I'd add it to Weblate by adding Hindi as an option there. 

> Can you guide me through this and tell me where am I missing anything?

Let me know if there are further questions!

> I have also requested the creation Hindi translations on weblate :) 

Feel free to send along the initial JSON and I'll add it to Weblate after 😊

**Comment by andrewtavis** [comment]
Closed by #63 :) :) Thanks so much for all the hard work, @KesharwaniArpita! 🚀
