### ISSUE TITLE
Start Scribe application Korean internationalization

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#53]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in an `ko.json` file to the [Scribe-i18n/jsons](https://github.com/scribe-org/Scribe-i18n/tree/main/Scribe-i18n/jsons) directory with a few localizations of some strings that are found in [Scribe-i18n/jsons/en-US.json](https://github.com/scribe-org/Scribe-i18n/blob/main/Scribe-i18n/jsons/en-US.json). This would thus start the i18n process for this language, with it also being added on to Scribe's [Weblate project](https://hosted.weblate.org/projects/scribe/scribe-i18n/) for further work.

Please let us know if you have interest in working on this, and we'll be happy to provide any help that's needed!

**Comment by pmj-chosim** [comment]
Hello:) I want to do this!

**Comment by andrewtavis** [comment]
Hey @pmj-chosim! This would be really cool! Feel free to make the `ko.json` file with any translations from `en-US.json` that you'd like to, and from there we can move to Weblate. On Weblate you can also get contributions on GitHub by linking your GitHub and Weblate accounts. If you're doing Hacktoberfest, then you won't be getting PRs for those, but you can get one for the first creation of the file for this issue 😊

**Comment by pmj-chosim** [comment]
Yeah! I see. Thank you. I'll on it right now

**Comment by andrewtavis** [comment]
Looking forward, @pmj-chosim!

**Comment by andrewtavis** [comment]
Hi @pmj-chosim 👋 Checking in here :) Anything I can do to support?

**Comment by yerimmii** [comment]
Hi! I want to join here:)

**Comment by andrewtavis** [comment]
Sure thing, @yerimmii! Goal now is the creation of a `kr.json` file with as many localizatiins from the `en-US.json` file that you want to do. From there we can continue on Weblate, or if you'd like to do the whole thing in the PR then that's also fine 😊

**Comment by andrewtavis** [comment]
I'd say maybe words like Wikimedia can be translated if there is an equivalent. For Scribe, I'm not sure 🤔 What are you used to seeing? Could we do something like `<KOREAN_FOR_SCRIBE>` - like putting it in quotes somehow to say that it's a direct translation? What would you suggest? :)

**Comment by yerimmii** [comment]
Personally, 'Scribe' seems simpler than <스크라이브>. In the case of Wikimedia, it is used in both English and Korean in Korea, so it seems better to translate it into Korean to match the sentence. Like <위키미디어>.

If it's okay to mix it together, can I look at the sentence and judge it on my own?

**Comment by yerimmii** [comment]
Oh, rather than having a separate word, in Korea, it is pronounced in Korean and used as a word.

**Comment by andrewtavis** [comment]
I think having Scribe in English and 위키미디어 for Wikimedia makes sense then :) The same for Wikidata, let's use it's Korean translation 😊

**Comment by yerimmii** [comment]
Okay :) Thank you!

**Comment by andrewtavis** [comment]
Thank you! Really looking forward to this 😊

**Comment by andrewtavis** [comment]
Closed by #73 🚀 Thanks for the support here, @yerimmii!
