### ISSUE TITLE
Improvements and Error Handling Suggestions for `convert_xcstrings_to_jsons.py`

### ISSUE THREAD

**Issue by OmarAI2003** [scribe-org/Scribe-i18n#57]
### Terms

- [x] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue)
- [x] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

I’m Omar, and I’ve been exploring the Scribe-i18n project as part of my contributions during outreachy contribution phase. I recently reviewed the `convert_xcstrings_to_jsons.py` script, which plays a crucial role in converting localization files.
### Suggested Improvements

- **File Handling**: Use context managers to ensure files are properly closed.
- **Error Handling**: Add error handling for file reading and JSON parsing.
- **Validation**: Check for the existence of required keys in the JSON structure before accessing them.
- **Language Handling**: Clarify how languages are determined to prevent unexpected behavior.
- **Directory Creation**: Ensure the destination directory exists or create it if necessary.

### Code Snippet

Here’s an example of how the file handling could be improved:

```python
with open(os.path.join(directory, "Localizable.xcstrings"), "r") as f:
    file = f.read()
```

I believe these changes can enhance the script's reliability and maintainability. I would love to hear your thoughts and am happy to assist in implementing these improvements if needed!

Thank you for your consideration!

**Comment by andrewtavis** [comment]
CC @Jag-Marcel and @angrezichatterbox here :)

I think that most of these are very solid suggestions, @OmarAI2003! One of them I'd argue is not needed:

> Validation: Check for the existence of required keys in the JSON structure before accessing them.

This is important, but we plan to do this with a GitHub action that another project of mine is working on :)

Aside from that, I'd say we'd welcome a PR with the other changes! Do you want to do one PR for `xcstrings` for iOS and then another PR for Android?

**Comment by OmarAI2003** [comment]
Thank you for the welcome and the feedback on my suggestions!

I wanted to clarify one point: Initially, I understood that changes in Scribe-i18n would propagate to the iOS and Android projects via subtrees, so I expected that a single PR here would update both platforms.

Could you please clarify why you prefer separate PRs for iOS and Android scripts?Your guidance would be really helpful so I can follow the preferred workflow!

**Comment by andrewtavis** [comment]
Ah what I mean is that we'd have one PR for `convert_xcstrings_to_jsons.py` and then one for `convert_strings_to_json.py`, the script for Android :) The PRs should just go here, and then we can port them to the iOS and Android apps via the subtrees 😊 You're welcome to do all the changes in one PR though!

**Comment by OmarAI2003** [comment]
Thank you for the clarification!

Starting with xcstrings, I’ll proceed with separate PRs for each script to keep the updates organized and easier to review.

**Comment by andrewtavis** [comment]
Sounds perfect :) Looking forward, @OmarAI2003!

**Comment by andrewtavis** [comment]
Do you want to continue to work in this issue for the improvements to the other scripts, @OmarAI2003? Or would you prefer another issue? Whatever works for you :)

**Comment by OmarAI2003** [comment]
Yes @andrewtavis , I'd really like to continue working on this issue! Could you please share what the next step would be for improving the other scripts? I'd be happy to contribute further.

**Comment by andrewtavis** [comment]
Haha writing across PRs and issues. Let's now do the opposite script for iOS, and from there we can move to Android :)

**Comment by andrewtavis** [comment]
Do you want to look into Android scripts at this point, @OmarAI2003? Then we can bring the work on Scribe-i18n to a close? If you wanted to do an Modern Standard Arabic localization of the app texts, I could also make an issue for that. I hope that MSA makes sense to start, as we're not at a point where we're doing dialects :)

**Comment by OmarAI2003** [comment]
> Do you want to look into Android scripts at this point, @OmarAI2003? Then we can bring the work on Scribe-i18n to a close?

Yes I'll start working on that very soon.

>  If you wanted to do an Modern Standard Arabic localization of the app texts, I could also make an issue for that. I hope that MSA makes sense to start, as we're not at a point where we're doing dialects :)


Yeah I'd welcome an issue for this, and indeed, MSA is a big thing for now.

**Comment by OmarAI2003** [comment]
Shoud I close this now and start working on #65?

**Comment by andrewtavis** [comment]
I'll close this when I merge the new PR, @OmarAI2003, but feel free to move to the other one 😊

**Comment by andrewtavis** [comment]
Closed by all the PRs above :) Thanks so much for your dedication here, @OmarAI2003! 😊
