### ISSUE TITLE
Start Scribe application Modern Standard Arabic internationalization

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#65]
### Terms

- [X] I have searched [open localization issues](https://github.com/scribe-org/Scribe-i18n/issues?q=is%3Aissue+is%3Aopen+label%3Alocalization)
- [X] I agree to follow Scribe-i18n's [Code of Conduct](https://github.com/scribe-org/Scribe-i18n/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in an `ar.json` file to the [Scribe-i18n/jsons](https://github.com/scribe-org/Scribe-i18n/tree/main/Scribe-i18n/jsons) directory with a few localizations of some strings that are found in [Scribe-i18n/jsons/en-US.json](https://github.com/scribe-org/Scribe-i18n/blob/main/Scribe-i18n/jsons/en-US.json). This would thus start the i18n process for this language, with it also being added on to Scribe's [Weblate project](https://hosted.weblate.org/projects/scribe/scribe-i18n/) for further work.

Please let us know if you have interest in working on this, and we'll be happy to provide any help that's needed!

**Comment by andrewtavis** [comment]
CC @OmarAI2003 :)

**Comment by OmarAI2003** [comment]
It seems that Weblate isn't supported on Windows, so I should install it on my Ubuntu.
![a](https://github.com/user-attachments/assets/12a772f8-b4fb-4fa5-b786-6236f331a79d)

**Comment by andrewtavis** [comment]
You can also use Weblate in the browser, @OmarAI2003 :)

**Comment by OmarAI2003** [comment]
I signed up, linked my GitHub account, added the scribe/i18n project, and made a request to start a new translation for Arabic. What should be the next step?
![a](https://github.com/user-attachments/assets/52f23dda-c1cc-4665-8dd5-4e7bd12e9d33)

**Comment by andrewtavis** [comment]
Now you can send a PR here with `ar.json` with as many translations as you want to start from `en-US.json`, and from there we merge that in and you can work on Weblate. You can also just do the full localization via the PR to add the file, and feel free to use machine translations and check the results!

**Comment by OmarAI2003** [comment]
Fine ok, for names like Scribe, GitHub, Matrix, etc., should I keep them as they are in the Arabic text or write them literally in Arabic?

**Comment by OmarAI2003** [comment]
I suggest for non-alphabetic languages to keep them as they are in the original English text, as they are brand names and widely recognized in their English form.

**Comment by andrewtavis** [comment]
If that's how it's normally done, then let's do it! Thanks for your input 😊

**Comment by OmarAI2003** [comment]
I'm experiencing a problem when displaying English and Arabic text on the same line. The order of the words changes due to the differences in text directionality: Arabic is right-to-left (RTL) while English is left-to-right (LTR)

Here for example , the word ordering is great, but when I copy this and paste it into my .json file in VSCode, it changes.
"يستخدم Scribe بيانات اللغة الموجودة في Wikidata للعديد من ميزاته الأساسية. نحصل على معلومات مثل أجناس الأسماء وتصريفات الأفعال وغير ذلك الكثير!"

**Comment by OmarAI2003** [comment]
Bro, this language is quite problematic I started to hate it more 😄😆😃 😃

**Comment by OmarAI2003** [comment]
> I'm experiencing a problem when displaying English and Arabic text on the same line. The order of the words changes due to the differences in text directionality: Arabic is right-to-left (RTL) while English is left-to-right (LTR)
> 
> Here for example , the word ordering is great, but when I copy this and paste it into my .json file in VSCode, it changes. 

"يستخدم Scribe بيانات اللغة الموجودة في Wikidata للعديد من ميزاته الأساسية. نحصل على معلومات مثل أجناس الأسماء وتصريفات الأفعال وغير ذلك الكثير!"

**Comment by andrewtavis** [comment]
If we want to find specific words for everything in Arabic, then we certainly can, @OmarAI2003 :)

**Comment by andrewtavis** [comment]
Directly from Wikidata Arabic labels:
- ويكي بيانات
- غيت هاب
- مؤسسة ويكيميديا

**Comment by andrewtavis** [comment]
And we could figure out something for Scribe and put it in quotes? Maybe translate it phonetically?

**Comment by OmarAI2003** [comment]
> I suggest for non-alphabetic languages to keep them as they are in the original English text, as they are brand names and widely recognized in their English form.

@andrewtavis so do you agree for this notion to be ignored?

**Comment by andrewtavis** [comment]
Ya let's actually translate the whole thing so there's no problem with LTR/RTL :)

**Comment by andrewtavis** [comment]
Closed by #68 :) I think that we could potentially translate Wikidata into Arabic in the future, @OmarAI2003. It's actually very common for the name of the platform to be in other languages :) But we can change that on Weblate 😊

**Comment by OmarAI2003** [comment]
Sure thing
