### ISSUE TITLE
Create GitHub action to update the .xcstrings file from Scribe-i18n

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-i18n#8]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-iOS/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-iOS' [Code of Conduct](https://github.com/scribe-org/Scribe-iOS/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Related to scribe-org/Scribe-i18n#9, it would be great if we created a GitHub Action that would automatically trigger the process in scribe-org/Scribe-i18n#9 when the Scribe-i18n files are updated in this repository. This would dramatically simplify the i18n workflow and make it so that someone doesn't need to run the update script locally.

### Contribution

@Jag-Marcel will be working on this as a part of GSoC ☀️ Can you write in here so I can assign? Let us know if and how we can help!

**Comment by andrewtavis** [comment]
And here we are in i18n then! 😊 Let's use this as proof of the work on this that you can then reference on Phabricator :)

**Comment by Jag-Marcel** [comment]
> The following is the error for the most recent run, @Jag-Marcel:
> 
> ```
> Run $diff = git diff --name-only HEAD^ HEAD
> fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-[10](https://github.com/scribe-org/Scribe-i18n/actions/runs/9490739220/job/26154796950#step:3:11)-11-github-actions-deprecating-save-state-and-set-output-commands/
> Error: Process completed with exit code 1.
> ```
> 
> Let me know what your thoughts are!

@andrewtavis If my research and thinking is correct, the first error should be because it doesn't actually fetch any of the recent commits. Maybe something like this could work at line 15:
```
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
```
For the second one, it should be `name=json_changed::$HasDiff >> $GITHUB_OUTPUT` instead of `::set-output name=json_changed::$HasDiff` at 25, I guess the guide I used was a bit outdated.
Let me know if it works this way!

**Comment by andrewtavis** [comment]
Do you want to open a PR, @Jag-Marcel, or should I make the changes? Up to you :) Will get it figured out before Saturday either way 😊

**Comment by Jag-Marcel** [comment]
I'll make a PR in a second 👍

**Comment by andrewtavis** [comment]
Thank you, @Jag-Marcel!

**Comment by andrewtavis** [comment]
As discussed, let's test this out in the dev sync and then we can close it afterwards, @Jag-Marcel. Thanks for the persistence here!

**Comment by andrewtavis** [comment]
Closing this out given the state of things 😊 Let's again discuss during the next sync as we were able to in the last one, @Jag-Marcel :)
